### PR TITLE
Improved dependencies for shs and shs_chosen

### PR DESCRIPTION
**Pull request by spleshka**

### CODE REVIEW

**Comment by rodrigoaguilera** [comment]
@spleshka I'm not sure I understand the change. You need version 2 of the module? 
Why not add it as an accepted version. This might break when they release version 3

**Comment by spleshka** [comment]
@rodrigoaguilera the issue is that we lock versions for no real reason - we don't have automated tests which would prove they work with one version and don't work with the other. Currently this approach we use created a lot of headache with upgrading the dependencies for real world projects. My gut feeling is that we should actually go the other way around for anu - don't lock versions for any package until we hit a case when certain version is not compatible with anu. Then we either fix it or lock the version.

**Comment by rodrigoaguilera** [comment]
Maybe shs is a case when a major upgrade is not likely to break things but I don't think it should be a general practice since it is still valuable to know the major version that was once compatible with anu instead of installing the latest stable version of a dependency, getting some error and not knowing if it is because a previous major version should be used.
I'm thinking more about fresh installs of anu. In a client installation this is not the case because you are supposed to lock the versions already.

**Comment by spleshka** [comment]
@rodrigoaguilera good point. I think we can create a job in circleci which would be trying to install anu lms with all latest dependencies on a daily basis, so that we'd be informed if some dependencies have any issues. Perhaps this approach is less painful than having to deal with updates for all dependencies. What do you think?

**Comment by rodrigoaguilera** [comment]
I'm ok with trying with a dependency like `shs`. Do you plan to constrain all dependencies with just an asterisk? 
I can see how it can ease the the updating of a project that needs a higher major version but from a project point of view I still don't see much value in ignoring the semantic versioning for dependencies because we lose valuable info about the dependencies.
The vast majority of projects/libraries/distros has some kind of constraint and having periodic testing will only make us aware that a stable branch is broken overnight.

**Comment by spleshka** [comment]
I don't have any strong bias here. We can go either way, however at the current stage we've already met issues with upgrading anu and its dependencies. So I tent to try avoiding hard locks (or in fact, avoid locks for projects which haven't moved to proper semver yet, because surely they will do it soon). I'll have a think what's the best way forward - I definitely understand the importance of locking at a major version.

**Pull request merged**
