### PR TITLE
[#181369329] Courses performance

### PR DESCRIPTION
**Pull request by i-amdroid**

### CODE REVIEW

**Comment by kalabro** [comment]
hey @rodrigoaguilera mind having a look when you have a moment? It's for 2.4 but will be eventually ported to 2.5 (with new progress)

**Review by bjuranic — APPROVED** [review]

**Review by rodrigoaguilera — CHANGES_REQUESTED** [review]
@i-amdroid Great stuff. Let me phrase a better changelog entry to see if understand the change.
```
Improved page loading performance by reducing the depth of references to load and explicitly loading lessons and quizzes.
```

**Comment by i-amdroid** [comment]
@rodrigoaguilera the idea of improvement is replacing heavy rest entity recursive function by relatively light function which returns only lessons and quizzes urls. We are not using other lesson and quizzes data from course object, we only need urls for offline mode. 
So one thing i would add to proposed entry is "urls" at the end.

```
Improved courses page loading performance by reducing the depth of references to load and explicitly loading lessons and quizzes urls.
```

**Review by rodrigoaguilera — APPROVED** [review]
Perfect tehn. Good to go from my side

**Pull request merged**
