### PR TITLE
Run eslint check on the ci.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**

### CODE REVIEW

**Comment by spleshka** [comment]
@rodrigoaguilera if you look at the output from `npm run eslint` you'll see that it clearly generated some output and the build should have failed, but it didn't: https://app.circleci.com/pipelines/github/systemseed/anu_lms/114/workflows/dbca19d8-f099-4c1c-bae6-fdb9a3ba4454/jobs/105

**Comment by rodrigoaguilera** [comment]
@spleshka 
from `.eslintrc.json`
```json
"rules": {
    "no-console": ["error", { "allow": ["error"] }],
    "react/prop-types": "warn"
  },
``` 
It is configured to just warn for `react/prop-types`. And all the output is about that eslint rule.
Looking at the git history I see is like that since the first 2.0 commit. 
Do you know why is configured this way?
Should all those warning be fixed now?

**Comment by spleshka** [comment]
@rodrigoaguilera I think we inherited this from previous version of ANU. So it's fine to change this to error and yes, they should be fixed in this PR then.

**Review by spleshka — APPROVED** [review]
Great job @rodrigoaguilera! Thank you very much for this PR.

**Pull request merged**
