### PR TITLE
Remove circular dependency on anu_lms_assessments.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**
anu_lms_assessments(Quiz) now depends on anu and not the other way
around. Now the modules can be installed without errors.

Introduce a plugin system to process data for each anu LMS content type.

Removed composer.lock as it is not used.
Updated rest_entity_recursive to get lates bugfixing.
Ensured compatibility with Drupal 9.

### CODE REVIEW

**Comment by spleshka** [comment]
@rodrigoaguilera first of all, huge shout out to you for the incredible work in this PR. It's incredible and it works! 

Looking and testing this PR I've found a couple of things to improve:

1. We need to add CHANGELOG record. Please, make it a rule for yourself to be updating CHANGELOG on each change. We have it for all our contributed projects.
2. Add hook_update which installs anu_lms_assessments module for smooth upgrade path for client projects
3. When anu_lms_assessments is enabled the paragraph with questions are not available in lessons automatically
3. When anu_lms_assessments is nstall we have anu_lms feature in the changed state. However, there are not much changes. Mainly they’re around legacy module node type - shall we get rid of it already? For other changes, shall we find a way to OK the changed configs? I think it's the right time for that.

**Comment by rodrigoaguilera** [comment]
@spleshka Thanks for reviewing thoroughly.

1. Done
2. AS we talked, in the current situation a client project will have both modules installed.
3. Added the [Paragraphs selection](https://www.drupal.org/project/paragraphs_selection) module to let paragraphs bundles decide the fields they should be listed on.
4. Did two things for having both modules in the default state in features. Removed the module (LEGACY) content type and not installing a default form mode for the paragraph `course_modules`. When both modules are installed there is a hook to swap to quiz form mode anyway and the default will be left unused.

Please have a look at the latest commits

**Comment by spleshka** [comment]
Great job @rodrigoaguilera! I've tested the anu installation again and found the following:

1. On anu_lms install I see warning ``` [error]  The field_course_modules entity reference field (entity_type: node, bundle: course) no longer has any valid bundle it can reference. The field is not working correctly anymore and has to be adjusted. ```. I think it's related to the field which now can be removed from the configs, because it was referencing module content type which is no longer available.
2. I couldn't add modules or lessons to courses anymore. There is no more form UI in place to do it.

**Comment by rodrigoaguilera** [comment]
@spleshka 
1- Removed the legacy field in the course
2- Since is not part of the config installed the form mode needed configuration. I added a hook_install to set the proper values

Please test again

**Comment by spleshka** [comment]
Tested @rodrigoaguilera - works perfectly well. Incredibly happy to get it in! Please, merge & create a new minor release for it.

**Review by spleshka — APPROVED** [review]

**Pull request merged**
